### PR TITLE
support xsd that has multiple complex types

### PR DESCRIPTION
**Pull request by jessicagood**
Modified models.py and models.html to support schemas with multiple layers.

### CODE REVIEW

**Comment by rclark** [comment]
I get a really odd behavior when I expand a field list, scroll down to the start of the second layer, and click the collapse button:

screen shot 2013-11-07 at 3 47 45 pm

Screen goes blank, then as soon as I scroll a little bit everything pops back in. This is using Chrome. Can you replicate that at all?

**Comment by rclark** [comment]
Now instead of getting a JSON list of field names, we will always get an object. That's great, we will need to accommodate that on the CKAN end -- thanks for taking care of it on `/models/`. 

I wonder about the inclusion in the object, though, of the "common" fields, which are not actually valid content model layers -- they're just XSD "shortcuts" to keep the file from being repetitive.

screen shot 2013-11-07 at 4 35 43 pm

We will have to talk to Steve about this. I don't know whether or not something in the XSD differentiates the common fields which aren't really a valid model layer from the ones that are.

**Comment by rclark** [comment]
@smrAzGS, these multi-layered XSD docs expose a set of ComplexTypes. Often there's one that is called `SampleAnalysisCommonType`, which defines attributes that the other types all inherit.

The questions are:
- Does this mean we could make a valid NGDS WFS with a featuretype called "SampleAnalysisCommon"?
- Is there anything unambiguous about this inherited type that we can use to distinguish it from other ComplexTypes defined in the XSD?

See comments above: https://github.com/usgin/modelmanager/pull/4#issuecomment-28018248 and https://github.com/usgin/modelmanager/pull/4#commitcomment-4542784

**Comment by jessicagood** [comment]
I can't replicate the issue https://github.com/usgin/modelmanager/pull/4#issuecomment-28014840 with the screen going blank when the Collapse Field Button is pressed. Works fine for me on Chrome in my Linux VM.

**Comment by rclark** [comment]
Great. If you can't replicate it then we won't worry about it until someone else complains.

**Comment by jessicagood** [comment]
Since we don't want to imply that "SampleAnalysisCommon" can be made into its own layer why don't I explicitly include each of the common fields in the field list for each layer? That's where they are supposed to be anyway. It's just going to make the models with multiple layers really long but it's probably easy for people to understand.

**Comment by rclark** [comment]
@jalisdairi this all looks good. We'll try to get @asonnenschein to fix the `type_details` function before merging this PR.

**Comment by jessicagood** [comment]
@rclark  Think field_info is better like this? Also, apparently all these xml files that I didn't change, and weren't indicated as changed when I did at git status before the commit and push, where push. Not sure why that happened.

**Comment by rclark** [comment]
Ahhhhhh `.idea/`

You probably need to revert that last commit and add `.idea/` to the .gitignore file.

**Pull request merged**
